version: 0.2

env:
  parameter-store:
    AWS_ACCESS_KEY_ID: "AccessKeyId"
    AWS_SECRET_ACCESS_KEY: "AccessKey"
    AdminConnectionString: "ParkingRotaDevelopmentAdminConnectionString"

phases:
  build:
    commands:
      - dotnet build
      - dotnet test ParkingRota.IntegrationTests
  post_build:
    commands:
      - chmod +x deploy.development.sh
      - ./deploy.development.sh