version: 0.2

env:
  parameter-store:
    AWS_ACCESS_KEY_ID: "AccessKeyId"
    AWS_SECRET_ACCESS_KEY: "AccessKey"
    ParkingRotaTestAdminConnectionString: "ParkingRotaTestAdminConnectionString"
    ParkingRotaTestConnectionString: "ParkingRotaTestConnectionString"
    ParkingRotaAdminConnectionString: "ParkingRotaAdminConnectionString"

phases:
  install:
    runtime-versions:
      dotnet: 2.2
  build:
    commands:
      - dotnet build
      - dotnet test ParkingRota.UnitTests
      - dotnet run --project ParkingRota.DatabaseUpgrader -e=ParkingRotaTestAdminConnectionString
      - dotnet test ParkingRota.IntegrationTests
  post_build:
    commands:
      - chmod +x deploy.sh
      - ./deploy.sh